### ISSUE TITLE
transition.redirect({page}) issue

### ISSUE THREAD

**Issue by JFusco** [webpack-contrib/react-proxy-loader#10] opened 2015-03-19 03:00 UTC
Routes.js file:

```
var React = require('react'),
Router = require('react-router'),
Route = Router.Route,
SomeApp = require('../components/SomeApp');

var Routes = (
    <Route handler={SomeApp}>
        <Route name="pageone" path='/' handler={require('react-proxy!../pages/PageOne')}/>
        <Route name="pagetwo" path='/pagetwo' handler={require('react-proxy!../pages/PageTwo')}/>
    </Route>
);

module.exports = Routes;
```

SomeApp.js file:

```
var React = require('react'),
Router = require('react-router'),
{Route, RouteHandler} = Router;


var SomeApp = React.createClass({
    statics: {
        willTransitionTo: function (transition, params, query, callback) {
            // This does nothing
            transition.redirect('pagetwo');
        }
    },

    render: function(){
        return (
            <div>
                <RouteHandler/>
            </div>
        );
    }
});

module.exports = SomeApp;
```

the transition.redirect method does not work when lazy loading modules.  Have you had this issue before?

Thanks!

**Comment by liouh** [comment] 2015-04-07 20:16
That's because willTransitionTo is only called on the proxy component, and not forwarded to the dynamically loaded component (SomeApp in your case).

The react-router specific version (https://github.com/odysseyscience/react-router-proxy-loader) does the proper handling for willTransitionTo and willTransitionFrom.

**Comment by JFusco** [comment] 2015-04-07 20:28
@liouh - Yes but, I'm using React 0.13.x which react-router >=0.13.x.  react-router-proxy-loader won't work with react-router 0.13.x yet.

**Comment by michael-ciniawsky** [comment] 2017-04-25 23:29
Closing as it seems this is fairly outdated, feel free to reopen if still relevant and any regressions with `react-proxy-loader` 😛

**Closed by michael-ciniawsky** 2017-04-25 23:29 UTC
